// The reference docs that come straight from the code, so they cannot drift.
// Written by scripts/emit-docs.ts, verified by tests/deploy/docs.test.ts and CI.
import { capabilityMarkdown } from '../authoring/index.ts';
import { createDefaultRegistry, defaultAdapterConfig } from '../capabilities/index.ts';
import { HELP } from '../cli/help.ts';

/** Every capability, including the ones that only exist when configured. */
function allCapabilities() {
  const base = defaultAdapterConfig();
  return createDefaultRegistry({
    ...base,
    shell: { ...base.shell, allowedCommands: ['/bin/true'] },
    datasources: { example: 'sqlite:///:memory:' },
    channels: { example: 'https://example.invalid/hook' },
    email: { smtpUrl: 'smtp://example.invalid', from: 'omniflow@example.invalid' },
    llm: { ...base.llm, apiKey: 'docs-only' },
  })
    .list()
    .map((c) => c.declaration);
}

export const OUTPUTS: Record<string, string> = {
  'docs/reference/capabilities.md': `<!-- Generated by \`npm run docs:generate\` from the capability declarations. Do not edit. -->\n\n${capabilityMarkdown(allCapabilities())}`,
  'docs/reference/cli.md': `<!-- Generated by \`npm run docs:generate\` from the CLI help. Do not edit. -->\n\n# Command-line reference\n\n\`\`\`text\n${HELP}\`\`\`\n`,
};
