// Generates the reference docs that come straight from the code, so they cannot drift:
//   docs/reference/capabilities.md   — every built-in capability's contract
//   docs/reference/cli.md            — the CLI's help text
//   npm run docs:generate            (writes)   ·   npm run docs:generate -- --check   (CI: fails if stale)
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { capabilityMarkdown } from '../authoring/index.ts';
import { createDefaultRegistry, defaultAdapterConfig } from '../capabilities/index.ts';
import { HELP } from '../cli/help.ts';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/** Every capability, including the ones that only exist when configured. */
function allCapabilities() {
  const base = defaultAdapterConfig();
  return createDefaultRegistry({
    ...base,
    shell: { ...base.shell, allowedCommands: ['/bin/true'] },
    datasources: { example: 'sqlite:///:memory:' },
    channels: { example: 'https://example.invalid/hook' },
    email: { smtpUrl: 'smtp://example.invalid', from: 'omniflow@example.invalid' },
    llm: { ...base.llm, apiKey: 'docs-only' },
  })
    .list()
    .map((c) => c.declaration);
}

export const OUTPUTS: Record<string, string> = {
  'docs/reference/capabilities.md': `<!-- Generated by \`npm run docs:generate\` from the capability declarations. Do not edit. -->\n\n${capabilityMarkdown(allCapabilities())}`,
  'docs/reference/cli.md': `<!-- Generated by \`npm run docs:generate\` from the CLI help. Do not edit. -->\n\n# Command-line reference\n\n\`\`\`text\n${HELP}\`\`\`\n`,
};

const check = process.argv.includes('--check');
let stale = 0;
for (const [file, content] of Object.entries(OUTPUTS)) {
  const path = join(root, file);
  if (check) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== content) {
      console.error(`${file} is out of date. Run: npm run docs:generate`);
      stale++;
    }
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
    console.log(`wrote ${file}`);
  }
}
if (check) {
  if (stale) process.exit(1);
  console.log('generated docs are up to date');
}
