// Generates THIRD_PARTY_NOTICES.md from the *production* dependency tree in package-lock.json.
//   npm run licenses          (writes the file)
//   npm run licenses -- --check   (fails if the file is out of date; used by CI)
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const lock = JSON.parse(readFileSync(join(root, 'package-lock.json'), 'utf8'));
const rows = [];
for (const [path, meta] of Object.entries(lock.packages)) {
  if (!path.startsWith('node_modules/') || meta.dev) continue;
  const name = path.replace(/^.*node_modules\//, '');
  const pkgFile = join(root, path, 'package.json');
  const pkg = existsSync(pkgFile) ? JSON.parse(readFileSync(pkgFile, 'utf8')) : {};
  const license = typeof meta.license === 'string' ? meta.license : typeof pkg.license === 'string' ? pkg.license : pkg.license?.type ?? 'UNKNOWN';
  const repo = (typeof pkg.repository === 'string' ? pkg.repository : pkg.repository?.url ?? pkg.homepage ?? '').replace(/^git\+/, '').replace(/\.git$/, '').replace(/^git:\/\//, 'https://');
  rows.push({ name, version: meta.version, license, repo });
}
rows.sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));

const odd = rows.filter((r) => /GPL|AGPL|SSPL|UNKNOWN|Commons-Clause/i.test(r.license));
const text = [
  '# Third-party notices',
  '',
  'OmniFlow is licensed under the Apache License 2.0 (see `LICENSE`). It includes the following third-party',
  'packages in its production dependency tree. Each is distributed under its own license; the license texts',
  'are included in the packages themselves (`node_modules/<name>/LICENSE`) and in the container image.',
  '',
  `Generated by \`npm run licenses\` from \`package-lock.json\` — ${rows.length} packages.`,
  '',
  ...(odd.length ? ['> **Review needed:** ' + odd.map((r) => `${r.name} (${r.license})`).join(', '), ''] : []),
  '| Package | Version | License | Source |',
  '|---|---|---|---|',
  ...rows.map((r) => `| ${r.name} | ${r.version} | ${r.license} | ${r.repo} |`),
  '',
].join('\n');

const out = join(root, 'THIRD_PARTY_NOTICES.md');
if (process.argv.includes('--check')) {
  if (!existsSync(out) || readFileSync(out, 'utf8') !== text) {
    console.error('THIRD_PARTY_NOTICES.md is out of date. Run: npm run licenses');
    process.exit(1);
  }
  console.log('THIRD_PARTY_NOTICES.md is up to date');
} else {
  writeFileSync(out, text);
  console.log(`wrote THIRD_PARTY_NOTICES.md (${rows.length} packages${odd.length ? `, ${odd.length} need review` : ''})`);
}
